insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A1","계열안내",'컴퓨터 정보 계열 챗봇에 오신 것을 환영합니다! 컴퓨터 정보 계열은 4개의 과로 이뤄져 있으며, 매년 80% 이상 최고의 취업률을 보이고 있습니다.  계열 안내 및 계열부장 인사말을 보시려면 아래 메뉴를 클릭해주세요',"https://com.yju.ac.kr/index.php?mid=page_OXGJ16");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A2","교수진소개",'컴퓨터 정보계열 챗봇이 소개하는!!! 컴퓨터 정보 계열엔 현재 훌륭한 스물 네분의 교수님들이 계십니다. 교수님들의 정보와 담당 과목을 보고 싶으시다면 아래 메뉴를 클릭해주세요',"https://com.yju.ac.kr/index.php?mid=board_Kwoo61");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A3","AI빅데이터응용소프트웨어과",'AI·빅데이터응용소프트웨어과는 인공지능, 빅데이터 분야 소프트웨어 개발자의 양성과 웹/모바일/IoT 분야 응용 소프트웨어 개발자 양성을 목표로 한 학과입니다. AI·빅데이터응용소프트웨어과의 자세한 정보를 보고 싶으시다면 아래 메뉴를 클릭해주세요.',"https://com.yju.ac.kr/index.php?mid=page_VrJT47");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A4","정보보안게임콘텐츠과",'정보보안·게임콘텐츠과는 클라우드 시스템 기반 보안 엔지니어의 양성과 메타버스 기반 게임 및 웹 콘텐츠 제작 전문가의 양성을 목적으로 두고 있는 학과입니다. 정보보안·게임콘텐츠과의 자세한 정보를 보고 싶으시다면 아래 메뉴를 클릭해주세요.',"https://com.yju.ac.kr/index.php?mid=page_wdSn56");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A5","AI클라우드프로그래밍과",'AI클라우드프로그래밍과는 4차 산업혁명 시대의 소프트웨어 개발자의 양성과 네트워크/서버 등 시스템 분야 전문 기술인재를 양성하는 학과입니다. 자세한 학과 소개를 보고 싶으시다면 아래 메뉴를 클릭해주세요',"https://com.yju.ac.kr/index.php?mid=page_GvQP63");
insert into web_link(Web_code, Web_name,Web_Contents ,Web_URL) values("230201A6","일본IT과",'일본IT과는 일본 IT기업 맞춤형 AI Big DaTa, 클라우드 시스템, 네트워크/보안등의 신기술을 활용할 수 있는 인재, 기획한 IT 서비스를 설계 및 개발을 할 수 있는 인재, 일본 원어민과 비즈니스 업무를 진행할 수 있는 일본어 능력을 갖춘 글로벌 인재를 양성하기 위한 학과로 14년간 총 419명, 8년 연속 100% 취업의 쾌거를 이룩했습니다. 학과의 자세한 정보를 보고 싶으시다면 아래 메뉴를 클릭해주세요.',"https://com.yju.ac.kr/index.php?mid=page_vhPi70");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A7","취업정보",'영진전문대학교 일자리플러스센터에서 운영하는 취업 정보센터에 오신 것을 환영합니다! 저희 취업 정보 센터에서는 채용정보와 심리검사, 지원서 작성방법들과 창업 지원과 경력 개발 시스템을 제공하고 있습니다. 취업 정보 및 센터에서 제공하는 다양한 정보를 얻고 싶으시다면 아래 메뉴를 클릭해주세요.
',"https://job.yju.ac.kr/");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A8","우수취업자인터뷰",'컴퓨터 정보 계열의 자랑! 우수취업자들의 인터뷰 모음을 불러왔어요. 선배분들의 팁과 자부심과 격려를 보고 싶으시다면 아래 메뉴를 클릭해주세요',"https://ipsi.yju.ac.kr/ipsi/164/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaXBzaSUyRjg5JTJGYXJ0Y2xMaXN0LmRvJTNGaXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjZzcmNoV3JkJTNEJTI2YmJzT3BlbldyZFNlcSUzRDExNSUyNnNyY2hDb2x1bW4lM0RhZGRJdGVtMDElMjY%3D");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201A9","입시Q&A",'컴퓨터 정보계열에 궁금한 점이나 전공, 과목에 대해 물어보고 싶은 것이 있다면 바로 여기 입시 Q&A 게시판에 물어보실 수 있어요. 질문이 있다면 아래 메뉴를 클릭해주세요!',"https://com.yju.ac.kr/index.php?mid=board_SYll62");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B1","컴정카탈로그",'컴퓨터 정보 계열에서 제공하는 계열 소개와 취업자 인터뷰를 총망라한 카탈로그를 불러왔어요! 아래 메뉴를 클릭하여 카탈로그를 보시고 꿈과 열정을 가지고 오세요!!
',"https://com.yju.ac.kr/index.php?mid=page_xPby79");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B2","학사공지",'컴퓨터정보계열 2023년 학사 공지를 조회했습니다!아래 메뉴를 클릭하면 학사 공지 게시판으로 이동하실 수 있습니다.',"https://com.yju.ac.kr/index.php?mid=board_NZIo01");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B3","학사일정",'영진전문대학 2023년 학사일정을 조회했습니다! 아래 메뉴를 클릭하면 학사일정을 확인할 수 있어요.',"https://www.yju.ac.kr/kr/3248/subview.do");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B4","증명서발급",'영진전문대학교 증명성 발급에 대해서 안내해드릴게요! 창구 발급 : 원스탑서비스센터(공학관 1층 101호) 소요시간 10분 이내, 증명서 무인발급기: 공학관 1층 Global Lounge에 설치된 증명서 무인발급기 이용(연중무휴 8:00 ~ 22:00) 인터넷 발급과 팩스 발급은 아래 메뉴를 클릭하시면 신청할 수 있어요!',"https://www.yju.ac.kr/kr/3255/subview.do");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B5","도서관",'미매를 여는 지혜 영진전문대 도서관을 찾아주셔서 감사합니다! 아래 메뉴를 클릭하여 도서관 홈페이지로 이동하시면 찾고 싶은 자료를 검색할 수 있고 다양한 도서관 서비스와 이벤트에 참여하실 수 있어요!',"https://lib.yju.ac.kr/WebYJC/Aspx/main/index.aspx");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B6","기숙사",'영진전문대학교 기숙사 정보를 찾아왔어요! 복현캠퍼스 생활관은 총 63실(2인실 46실, 4인실 17실)이고, 글로벌 캠퍼스 생활관은 A동(224실), B동(312실)로 이뤄져 있어요. 아래 메뉴를 클릭하면 생활관 공지사항과 신청 및 발표 정보를 확인하실 수 있습니다.',"https://www.yju.ac.kr/kr/3274/subview.do");
insert into web_link(Web_code, Web_name, Web_Contents ,Web_URL) values("230201B7","인공지능사업",'신기술 분야 공유대학 체계 구축과 인공지능 분야 디지털 신기술 인재양성을 위한 혁신공유대학 사업! 혁신공유대학 사업단의 정보를 불러왔습니다! 현재 혁신공유대학사업단은 인공지능 마일리지 장학금 제도와 마이크디그리 학위제도 및 공유사업단에 참여하는 대학간 학점 교류와 전문가 특강 등을 제공하고 있습니다.',"https://aicoss.yju.ac.kr/");